kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - configmaps
      - services
      - sparkapplications
      - persistentvolumeclaims
